apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: boolv-ai-tools-docker
spec:
  encryptedData:
    .dockerconfigjson: AQBoMyBnYOFvDKieW2oQb3XVhHiKIA0zHharV6f9hq81ItMTR5ko3VNl/1jgU/bcruf9646tUQyUL9iILcbYie0D1Ye9NDFJGmCJhOGKt8QIiCELYio0DpD/fF1xZBvpASeYBEuM2KSEvwGzOuZG3lAmDbn5SB3gSMjnvj6sxokzYpj7k3y+1Pt0ZtQEQ7zAeexQQnuLL2LYmHuccW2dU4elsRCkDHrrkGB2HWEsZBvdrIkb5QAH/8jJMe0c5ow8/DZ24ZbHeo/Hrd/bQXdXD2iupqncnpBGse+N2KxRdF6zLpd9+VU2qkYJy7kyf66oiCmXf7HrQwsyZXoDD6dP72evD0H0Tuy5aOEKE8oUulPqyxQ18Ada6DtKXuJyP6oVuZ71sQCTUEKVkGL7kfIiRGazmW8M2GaAfRjibexx7l136RwopugtVCPL2GYt3R9VyPC7pCznvaCHVw7bAP39AUGL4YoRKLtecOEPHy1F4DG3tON4w0wVW78/HcbPMbgDyZiAHBsphyhwvBsHMzP8PAGlwBnbStkRtehhIvkMyx1+Ojv6hYybExWPUbVwKz6/br8Gd28O/Mobqr0QyuA=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: boolv-ai-tools-docker
    type: kubernetes.io/dockerconfigjson
